In [1]:
# try reading the gzips

import tqdm
import pandas as pd
import tempfile
import csv
import gzip
import xml.etree.cElementTree as ET
import glob
import random
from readers import pmreader2 as pmreader
import json
import sys
import os

In [2]:
def abstract_plaintext(abstract):
    out = []
    for sec in abstract:
        if sec["header"] != "_UNSTRUCTURED":
            out.append(sec["header"])
        out.append(sec["text"])

    return "\n".join(out)

In [3]:
def iter_abstracts(filename, num_to_select = None):
    with open(filename, 'rb') as f:
        decompressedFile = gzip.GzipFile(fileobj=f, mode='rb')
        xml_dump = decompressedFile.read()
        xml_parsed = ET.fromstring(xml_dump)
        articles = xml_parsed.findall('PubmedArticle/MedlineCitation')
        if num_to_select:
            article_sample = random.sample(articles, num_to_select)
        else:
            article_sample = articles
        for j, article in enumerate(tqdm.tqdm(article_sample)):
            p_article = pmreader.PubmedCorpusReader(xml_ET=article)
            yield p_article.to_dict()

In [4]:
    num_to_select = None
    seed = 42

    train_set_size = 8000000
    val_set_size = 600000
    test_non_sys_size = 600000
    test_sys_size = 300000 

    filenames = glob.glob('/data/iain/pubmed/*.gz')
#     all_data = []


    is_train_data = False
    is_val_data = False
    is_test_sys_data = False
    is_test_non_sys_data = False
    
    
    train_data = pd.DataFrame()
    val_data = pd.DataFrame()
    test_non_sys_data = pd.DataFrame()
    test_sys_data = pd.DataFrame()


    num_todo = len(filenames)
    
    train_per_file = round(train_set_size/num_todo)
    val_per_file = round(val_set_size/num_todo)
    test_non_sys_per_file = round(test_non_sys_size/num_todo)
    test_sys_size_per_file = round(test_sys_size/num_todo)
#     for i, fn in tqdm.tqdm(enumerate(filenames)): # this line does *all* >900 files (takes ages)
    # for id in range(len(filenames)):
    for i, fn in tqdm.tqdm(enumerate([filenames[900]])): # file 900 looks to me to be a decent example; perhaps others better! but some earlier abstracts don't contain much info


            # here we're iterating through *all* files
            # in the final version, probably we'd want to randomly sample, to generate a manageable amount of data
            # I suspect we might not have enough RAM to hold all 300M articles at once, (and so you will need to sample in the loop)
            # but possibly it might work without this, and you could sample from the Pandas dataframe below instead!
            sys.__stdout__.write("file number {}/{} ({}) processing \n".format(i, num_todo, fn)) # optional to see progress from terminal
            print("file number {}/{} ({}) processing \n".format(i, num_todo, fn))
            data = []
            print(fn)
            
            if len(train_data) > train_set_size and len(val_data) > val_set_size and len(test_non_sys_data) > test_non_sys_size and len(test_sys_data) > test_sys_size:
                    break
            
            try:
                for article in iter_abstracts(fn, num_to_select):
                    data.append(article)

                data_pd = pd.DataFrame(data)
                data_pd = data_pd[data_pd['year'] != '']
                data_pd['year'] = list(map(int, data_pd['year']))
                
                
                if len(train_data) < train_set_size:
                    print('entered train')
                    train_subset = data_pd[(data_pd['year']>=1987) & (data_pd['year']<=2014)]
                    if not is_train_data:
                        train_data = train_subset
                        is_train_data = True
                    else:
                        train_data = pd.concat([train_data, train_subset])
                    train_data.to_csv('pubmed_articles_train.csv')
                
                if len(val_data) < val_set_size:
                    print('entered val')
                    val_subset = data_pd[data_pd['year']==2015]
                    if not is_val_data:
                        val_data = val_subset
                        is_val_data = True
                    else:
                        val_data = pd.concat([val_data, val_subset])
                    val_data.to_csv('pubmed_articles_val.csv')
                    
                if len(test_non_sys_data) < test_non_sys_size:
                    print('entered test_non_sys')
                    test_non_sys_subset = data_pd[data_pd['year']==2016]
                    if not is_test_non_sys_data:
                        test_non_sys_data = test_non_sys_subset
                        is_test_non_sys_data = True
                    else:
                        test_non_sys_data = pd.concat([test_non_sys_data, test_non_sys_subset])
                    test_non_sys_data.to_csv('pubmed_articles_test_non_sys.csv')
                    
                if len(test_sys_data) < test_sys_size:
                    print('entered test_sys')
                    test_sys_subset = data_pd[data_pd['year']==2019]
                    if not is_test_sys_data:
                        test_sys_data = test_sys_subset
                        is_test_sys_data = True
                    else:
                        test_sys_data = pd.concat([test_sys_data, test_sys_subset])
                    test_sys_data.to_csv('pubmed_articles_test_sys.csv')
                
            except:
                pass

0it [00:00, ?it/s]

file number 0/1062 (/data/iain/pubmed/pubmed21n0905.xml.gz) processing

/data/iain/pubmed/pubmed21n0905.xml.gz

  0%|          | 0/30000 [00:00<?, ?it/s]
  0%|          | 106/30000 [00:00<00:28, 1059.52it/s]
  1%|          | 225/30000 [00:00<00:26, 1132.65it/s]
  1%|          | 366/30000 [00:00<00:23, 1257.99it/s]
  2%|▏         | 517/30000 [00:00<00:21, 1354.19it/s]
  2%|▏         | 653/30000 [00:00<00:23, 1235.59it/s]
  3%|▎         | 779/30000 [00:00<00:24, 1212.12it/s]
  3%|▎         | 902/30000 [00:00<00:24, 1178.31it/s]
  3%|▎         | 1021/30000 [00:00<00:24, 1174.89it/s]
  4%|▍         | 1139/30000 [00:00<00:26, 1097.13it/s]
  4%|▍         | 1263/30000 [00:01<00:25, 1134.56it/s]
  5%|▍         | 1378/30000 [00:01<00:26, 1076.20it/s]
  5%|▍         | 1487/30000 [00:01<00:27, 1049.02it/s]
  5%|▌         | 1593/30000 [00:01<00:27, 1027.77it/s]
  6%|▌         | 1715/30000 [00:01<00:26, 1079.63it/s]
  6%|▌         | 1829/30000 [00:01<00:25, 1095.94it/s]
  6%|▋         | 1940/30000 [00:01<00:28, 971.17it/s]
  7%|▋         | 2040/30000 [00:01<00:29, 946.97it/s]
  7%|▋         | 2137/30000 [00:01<00:29, 934.37it/s]
  7%|▋         | 2233/30000 [00:02<00:29, 939.57it/s]
  8%|▊         | 2328/30000 [00:02<00:30, 911.13it/s]
  8%|▊         | 2426/30000 [00:02<00:29, 929.44it/s]
  8%|▊         | 2520/30000 [00:02<00:29, 923.98it/s]
  9%|▊         | 2613/30000 [00:02<00:29, 925.08it/s]
  9%|▉         | 2724/30000 [00:02<00:27, 978.87it/s]
 10%|▉         | 2864/30000 [00:02<00:24, 1101.52it/s]
 10%|▉         | 2996/30000 [00:02<00:23, 1163.67it/s]
 10%|█         | 3113/30000 [00:02<00:23, 1157.26it/s]
 11%|█         | 3230/30000 [00:03<00:23, 1139.45it/s]
 11%|█         | 3354/30000 [00:03<00:22, 1166.56it/s]
 12%|█▏        | 3471/30000 [00:03<00:23, 1132.18it/s]
 12%|█▏        | 3586/30000 [00:03<00:23, 1135.16it/s]
 12%|█▏        | 3700/30000 [00:03<00:23, 1122.96it/s]
 13%|█▎        | 3815/30000 [00:03<00:23, 1128.51it/s]
 13%|█▎        | 3928/30000 [00:03<00:23, 1119.05it/s]
 13%|█▎        | 4040/30000 [00:03<00:23, 1115.85it/s]
 14%|█▍        | 4158/30000 [00:03<00:22, 1132.30it/s]
 14%|█▍        | 4284/30000 [00:03<00:21, 1169.41it/s]
 15%|█▍        | 4402/30000 [00:04<00:22, 1150.69it/s]
 15%|█▌        | 4518/30000 [00:04<00:23, 1085.78it/s]
 15%|█▌        | 4628/30000 [00:04<00:23, 1077.81it/s]
 16%|█▌        | 4737/30000 [00:04<00:23, 1061.39it/s]
 16%|█▌        | 4844/30000 [00:04<00:24, 1010.87it/s]
 16%|█▋        | 4946/30000 [00:04<00:24, 1011.73it/s]
 17%|█▋        | 5062/30000 [00:04<00:23, 1052.66it/s]
 17%|█▋        | 5182/30000 [00:04<00:22, 1095.11it/s]
 18%|█▊        | 5299/30000 [00:04<00:22, 1115.31it/s]
 18%|█▊        | 5456/30000 [00:04<00:19, 1246.61it/s]
 19%|█▊        | 5582/30000 [00:05<00:22, 1096.87it/s]
 19%|█▉        | 5696/30000 [00:05<00:23, 1033.56it/s]
 19%|█▉        | 5803/30000 [00:05<00:24, 970.29it/s]
 20%|█▉        | 5903/30000 [00:05<00:25, 943.25it/s]
 20%|██        | 6008/30000 [00:05<00:24, 969.59it/s]
 20%|██        | 6110/30000 [00:05<00:24, 982.58it/s]
 21%|██        | 6234/30000 [00:05<00:22, 1054.83it/s]
 21%|██▏       | 6378/30000 [00:05<00:20, 1164.83it/s]
 22%|██▏       | 6501/30000 [00:06<00:19, 1181.91it/s]
 22%|██▏       | 6630/30000 [00:06<00:19, 1212.97it/s]
 23%|██▎       | 6753/30000 [00:06<00:19, 1172.84it/s]
 23%|██▎       | 6872/30000 [00:06<00:19, 1165.59it/s]
 23%|██▎       | 6990/30000 [00:06<00:20, 1131.25it/s]
 24%|██▎       | 7106/30000 [00:06<00:20, 1138.52it/s]
 24%|██▍       | 7221/30000 [00:06<00:20, 1138.58it/s]
 24%|██▍       | 7336/30000 [00:06<00:20, 1088.30it/s]
 25%|██▍       | 7446/30000 [00:06<00:21, 1035.83it/s]
 25%|██▌       | 7560/30000 [00:06<00:21, 1062.49it/s]
 26%|██▌       | 7673/30000 [00:07<00:20, 1078.96it/s]
 26%|██▌       | 7782/30000 [00:07<00:20, 1063.14it/s]
 26%|██▋       | 7889/30000 [00:07<00:20, 1062.63it/s]
 27%|██▋       | 7996/30000 [00:07<00:21, 1026.44it/s]
 27%|██▋       | 8109/30000 [00:07<00:20, 1053.66it/s]
 27%|██▋       | 8215/30000 [00:07<00:20, 1049.59it/s]
 28%|██▊       | 8323/30000 [00:07<00:20, 1057.16it/s]
 28%|██▊       | 8429/30000 [00:07<00:20, 1048.45it/s]
 28%|██▊       | 8534/30000 [00:07<00:20, 1034.79it/s]
 29%|██▉       | 8650/30000 [00:08<00:19, 1068.47it/s]
 29%|██▉       | 8762/30000 [00:08<00:19, 1081.95it/s]
 30%|██▉       | 8871/30000 [00:08<00:20, 1040.74it/s]
 30%|██▉       | 8976/30000 [00:08<00:20, 1027.05it/s]
 30%|███       | 9079/30000 [00:08<00:20, 1024.65it/s]
 31%|███       | 9182/30000 [00:08<00:20, 999.27it/s]
 31%|███       | 9283/30000 [00:08<00:22, 936.43it/s]
 31%|███▏      | 9378/30000 [00:08<00:22, 925.75it/s]
 32%|███▏      | 9476/30000 [00:08<00:21, 938.89it/s]
 32%|███▏      | 9573/30000 [00:08<00:21, 945.73it/s]
 32%|███▏      | 9668/30000 [00:09<00:22, 918.09it/s]
 33%|███▎      | 9761/30000 [00:09<00:22, 902.52it/s]
 33%|███▎      | 9852/30000 [00:09<00:22, 894.50it/s]
 33%|███▎      | 9949/30000 [00:09<00:21, 915.05it/s]
 33%|███▎      | 10041/30000 [00:09<00:22, 906.93it/s]
 34%|███▍      | 10132/30000 [00:09<00:21, 905.51it/s]
 34%|███▍      | 10242/30000 [00:09<00:20, 962.23it/s]
 35%|███▍      | 10361/30000 [00:09<00:19, 1026.84it/s]
 35%|███▍      | 10464/30000 [00:09<00:19, 1020.22it/s]
 35%|███▌      | 10587/30000 [00:09<00:17, 1081.03it/s]
 36%|███▌      | 10723/30000 [00:10<00:16, 1160.73it/s]
 36%|███▌      | 10845/30000 [00:10<00:16, 1176.22it/s]
 37%|███▋      | 10963/30000 [00:10<00:17, 1070.38it/s]
 37%|███▋      | 11072/30000 [00:10<00:17, 1065.45it/s]
 37%|███▋      | 11180/30000 [00:10<00:18, 1004.71it/s]
 38%|███▊      | 11292/30000 [00:10<00:18, 1034.13it/s]
 38%|███▊      | 11421/30000 [00:10<00:16, 1103.62it/s]
 38%|███▊      | 11533/30000 [00:10<00:17, 1070.17it/s]
 39%|███▉      | 11642/30000 [00:10<00:17, 1045.00it/s]
 39%|███▉      | 11748/30000 [00:11<00:20, 885.14it/s]
 39%|███▉      | 11841/30000 [00:11<00:26, 690.21it/s]
 40%|███▉      | 11956/30000 [00:11<00:22, 789.31it/s]
 40%|████      | 12049/30000 [00:11<00:21, 821.84it/s]
 41%|████      | 12163/30000 [00:11<00:19, 902.06it/s]
 41%|████      | 12261/30000 [00:11<00:19, 899.08it/s]
 41%|████      | 12374/30000 [00:11<00:18, 959.20it/s]
 42%|████▏     | 12474/30000 [00:11<00:18, 933.89it/s]
 42%|████▏     | 12571/30000 [00:12<00:18, 937.29it/s]
 42%|████▏     | 12667/30000 [00:12<00:18, 930.02it/s]
 43%|████▎     | 12762/30000 [00:12<00:18, 933.21it/s]
 43%|████▎     | 12857/30000 [00:12<00:18, 917.07it/s]
 43%|████▎     | 12950/30000 [00:12<00:18, 907.80it/s]
 44%|████▎     | 13063/30000 [00:12<00:17, 971.55it/s]
 44%|████▍     | 13178/30000 [00:12<00:16, 1022.29it/s]
 44%|████▍     | 13281/30000 [00:12<00:17, 971.77it/s]
 45%|████▍     | 13380/30000 [00:12<00:17, 972.96it/s]
 45%|████▍     | 13479/30000 [00:13<00:16, 974.39it/s]
 45%|████▌     | 13577/30000 [00:13<00:18, 906.01it/s]
 46%|████▌     | 13669/30000 [00:13<00:18, 900.73it/s]
 46%|████▌     | 13786/30000 [00:13<00:16, 975.57it/s]
 46%|████▋     | 13908/30000 [00:13<00:15, 1042.28it/s]
 47%|████▋     | 14015/30000 [00:13<00:15, 1050.27it/s]
 47%|████▋     | 14124/30000 [00:13<00:14, 1059.50it/s]
 47%|████▋     | 14231/30000 [00:13<00:15, 1033.39it/s]
 48%|████▊     | 14335/30000 [00:13<00:15, 1027.93it/s]
 48%|████▊     | 14439/30000 [00:13<00:15, 1008.45it/s]
 48%|████▊     | 14548/30000 [00:14<00:14, 1031.67it/s]
 49%|████▉     | 14662/30000 [00:14<00:14, 1060.44it/s]
 49%|████▉     | 14769/30000 [00:14<00:14, 1018.25it/s]
 50%|████▉     | 14873/30000 [00:14<00:14, 1023.92it/s]
 50%|████▉     | 14976/30000 [00:14<00:14, 1009.62it/s]
 50%|█████     | 15083/30000 [00:14<00:14, 1024.16it/s]
 51%|█████     | 15188/30000 [00:14<00:14, 1030.65it/s]
 51%|█████     | 15296/30000 [00:14<00:14, 1037.87it/s]
 51%|█████▏    | 15400/30000 [00:14<00:14, 1024.05it/s]
 52%|█████▏    | 15503/30000 [00:15<00:14, 1000.50it/s]

 52%|█████▏    | 15614/30000 [00:15<00:13, 1031.64it/s]
 52%|█████▏    | 15720/30000 [00:15<00:13, 1038.64it/s]
 53%|█████▎    | 15825/30000 [00:15<00:13, 1034.70it/s]
 53%|█████▎    | 15929/30000 [00:15<00:14, 998.54it/s]
 53%|█████▎    | 16030/30000 [00:15<00:14, 968.50it/s]
 54%|█████▍    | 16128/30000 [00:15<00:14, 942.63it/s]
 54%|█████▍    | 16223/30000 [00:15<00:14, 922.50it/s]
 54%|█████▍    | 16332/30000 [00:15<00:14, 969.64it/s]
 55%|█████▍    | 16483/30000 [00:15<00:12, 1123.08it/s]
 55%|█████▌    | 16623/30000 [00:16<00:11, 1203.21it/s]
 56%|█████▌    | 16765/30000 [00:16<00:10, 1264.14it/s]
 56%|█████▋    | 16896/30000 [00:16<00:10, 1277.27it/s]
 57%|█████▋    | 17025/30000 [00:16<00:10, 1190.74it/s]
 57%|█████▋    | 17146/30000 [00:16<00:11, 1122.35it/s]
 58%|█████▊    | 17260/30000 [00:16<00:11, 1081.81it/s]
 58%|█████▊    | 17370/30000 [00:16<00:12, 1006.79it/s]
 58%|█████▊    | 17477/30000 [00:16<00:12, 1022.97it/s]
 59%|█████▊    | 17581/30000 [00:16<00:12, 1023.38it/s]
 59%|█████▉    | 17687/30000 [00:17<00:11, 1033.02it/s]
 59%|█████▉    | 17791/30000 [00:17<00:12, 996.13it/s]
 60%|█████▉    | 17893/30000 [00:17<00:12, 1001.83it/s]
 60%|██████    | 18000/30000 [00:17<00:11, 1021.00it/s]
 60%|██████    | 18103/30000 [00:17<00:12, 975.23it/s]
 61%|██████    | 18220/30000 [00:17<00:11, 1028.47it/s]
 61%|██████    | 18326/30000 [00:17<00:11, 1035.28it/s]
 61%|██████▏   | 18441/30000 [00:17<00:10, 1067.08it/s]
 62%|██████▏   | 18549/30000 [00:17<00:11, 1009.73it/s]
 62%|██████▏   | 18651/30000 [00:18<00:11, 1006.18it/s]
 63%|██████▎   | 18753/30000 [00:18<00:11, 952.73it/s]
 63%|██████▎   | 18850/30000 [00:18<00:11, 955.53it/s]
 63%|██████▎   | 18959/30000 [00:18<00:11, 993.02it/s]
 64%|██████▎   | 19059/30000 [00:18<00:11, 984.76it/s]
 64%|██████▍   | 19172/30000 [00:18<00:10, 1025.31it/s]
 64%|██████▍   | 19291/30000 [00:18<00:09, 1073.01it/s]
 65%|██████▍   | 19399/30000 [00:18<00:10, 1058.35it/s]
 65%|██████▌   | 19506/30000 [00:18<00:10, 1012.50it/s]
 65%|██████▌   | 19608/30000 [00:18<00:10, 992.09it/s]
 66%|██████▌   | 19711/30000 [00:19<00:10, 1000.89it/s]
 66%|██████▌   | 19825/30000 [00:19<00:09, 1040.68it/s]
 66%|██████▋   | 19930/30000 [00:19<00:10, 981.46it/s]
 67%|██████▋   | 20042/30000 [00:19<00:09, 1016.42it/s]
 67%|██████▋   | 20145/30000 [00:19<00:09, 1002.30it/s]
 67%|██████▋   | 20246/30000 [00:19<00:09, 982.47it/s]
 68%|██████▊   | 20345/30000 [00:19<00:10, 935.04it/s]
 68%|██████▊   | 20452/30000 [00:19<00:09, 970.73it/s]
 68%|██████▊   | 20550/30000 [00:19<00:10, 942.94it/s]
 69%|██████▉   | 20645/30000 [00:20<00:09, 936.18it/s]
 69%|██████▉   | 20751/30000 [00:20<00:09, 969.84it/s]
 69%|██████▉   | 20849/30000 [00:20<00:09, 967.72it/s]
 70%|██████▉   | 20961/30000 [00:20<00:08, 1011.95it/s]
 70%|███████   | 21099/30000 [00:20<00:07, 1119.07it/s]
 71%|███████   | 21230/30000 [00:20<00:07, 1174.28it/s]
 71%|███████   | 21352/30000 [00:20<00:07, 1187.57it/s]
 72%|███████▏  | 21472/30000 [00:20<00:07, 1168.65it/s]
 72%|███████▏  | 21590/30000 [00:20<00:07, 1107.08it/s]
 72%|███████▏  | 21702/30000 [00:20<00:07, 1081.00it/s]
 73%|███████▎  | 21811/30000 [00:21<00:07, 1056.12it/s]
 73%|███████▎  | 21927/30000 [00:21<00:07, 1082.89it/s]
 73%|███████▎  | 22036/30000 [00:21<00:07, 1046.52it/s]
 74%|███████▍  | 22145/30000 [00:21<00:07, 1056.25it/s]
 74%|███████▍  | 22257/30000 [00:21<00:07, 1073.55it/s]
 75%|███████▍  | 22365/30000 [00:21<00:07, 1058.49it/s]
 75%|███████▍  | 22472/30000 [00:21<00:07, 1060.55it/s]
 75%|███████▌  | 22593/30000 [00:21<00:06, 1101.60it/s]
 76%|███████▌  | 22704/30000 [00:21<00:06, 1080.57it/s]
 76%|███████▌  | 22820/30000 [00:22<00:06, 1103.31it/s]
 76%|███████▋  | 22936/30000 [00:22<00:06, 1118.56it/s]
 77%|███████▋  | 23049/30000 [00:22<00:06, 1119.75it/s]
 77%|███████▋  | 23162/30000 [00:22<00:06, 1115.60it/s]
 78%|███████▊  | 23274/30000 [00:22<00:06, 1038.58it/s]
 78%|███████▊  | 23379/30000 [00:22<00:06, 1017.42it/s]
 78%|███████▊  | 23490/30000 [00:22<00:06, 1042.93it/s]
 79%|███████▊  | 23595/30000 [00:22<00:06, 984.07it/s]
 79%|███████▉  | 23695/30000 [00:22<00:06, 948.29it/s]
 79%|███████▉  | 23791/30000 [00:23<00:06, 920.69it/s]
 80%|███████▉  | 23896/30000 [00:23<00:06, 955.82it/s]
 80%|███████▉  | 23993/30000 [00:23<00:06, 910.20it/s]
 80%|████████  | 24090/30000 [00:23<00:06, 926.03it/s]
 81%|████████  | 24214/30000 [00:23<00:05, 1014.72it/s]
 81%|████████  | 24353/30000 [00:23<00:05, 1122.04it/s]
 82%|████████▏ | 24477/30000 [00:23<00:04, 1153.42it/s]
 82%|████████▏ | 24594/30000 [00:23<00:05, 1060.76it/s]
 82%|████████▏ | 24703/30000 [00:23<00:05, 999.08it/s]
 83%|████████▎ | 24805/30000 [00:24<00:05, 957.43it/s]
 83%|████████▎ | 24903/30000 [00:24<00:05, 930.78it/s]
 83%|████████▎ | 25014/30000 [00:24<00:05, 978.47it/s]
 84%|████████▍ | 25162/30000 [00:24<00:04, 1117.96it/s]
 84%|████████▍ | 25276/30000 [00:24<00:04, 1066.95it/s]
 85%|████████▍ | 25386/30000 [00:24<00:04, 1074.25it/s]
 85%|████████▍ | 25495/30000 [00:24<00:04, 1054.45it/s]
 85%|████████▌ | 25606/30000 [00:24<00:04, 1069.17it/s]
 86%|████████▌ | 25714/30000 [00:24<00:04, 1063.76it/s]
 86%|████████▌ | 25821/30000 [00:24<00:03, 1053.49it/s]
 86%|████████▋ | 25940/30000 [00:25<00:03, 1092.54it/s]
 87%|████████▋ | 26050/30000 [00:25<00:03, 1092.68it/s]
 87%|████████▋ | 26160/30000 [00:25<00:03, 1050.78it/s]
 88%|████████▊ | 26266/30000 [00:25<00:03, 990.34it/s]
 88%|████████▊ | 26366/30000 [00:25<00:03, 957.23it/s]
 88%|████████▊ | 26465/30000 [00:25<00:03, 966.21it/s]
 89%|████████▊ | 26570/30000 [00:25<00:03, 988.89it/s]
 89%|████████▉ | 26697/30000 [00:25<00:03, 1065.90it/s]
 89%|████████▉ | 26805/30000 [00:25<00:03, 1053.73it/s]
 90%|████████▉ | 26911/30000 [00:26<00:03, 1010.31it/s]
 90%|█████████ | 27013/30000 [00:26<00:03, 987.29it/s]
 90%|█████████ | 27113/30000 [00:26<00:03, 929.88it/s]
 91%|█████████ | 27209/30000 [00:26<00:02, 935.19it/s]
 91%|█████████ | 27327/30000 [00:26<00:02, 1000.84it/s]
 92%|█████████▏| 27473/30000 [00:26<00:02, 1130.10it/s]
 92%|█████████▏| 27593/30000 [00:26<00:02, 1149.47it/s]
 92%|█████████▏| 27727/30000 [00:26<00:01, 1204.97it/s]
 93%|█████████▎| 27849/30000 [00:26<00:01, 1205.56it/s]
 93%|█████████▎| 27997/30000 [00:26<00:01, 1285.78it/s]
 94%|█████████▍| 28156/30000 [00:27<00:01, 1375.97it/s]
 94%|█████████▍| 28297/30000 [00:27<00:01, 1383.87it/s]
 95%|█████████▍| 28436/30000 [00:27<00:01, 1361.88it/s]
 95%|█████████▌| 28573/30000 [00:27<00:01, 1336.19it/s]
 96%|█████████▌| 28707/30000 [00:27<00:01, 1260.51it/s]
 96%|█████████▌| 28834/30000 [00:27<00:00, 1193.59it/s]
 97%|█████████▋| 28955/30000 [00:27<00:00, 1145.64it/s]
 97%|█████████▋| 29071/30000 [00:27<00:00, 1117.41it/s]
 97%|█████████▋| 29184/30000 [00:27<00:00, 1085.22it/s]
 98%|█████████▊| 29293/30000 [00:28<00:00, 1074.84it/s]
 98%|█████████▊| 29407/30000 [00:28<00:00, 1091.32it/s]
 98%|█████████▊| 29517/30000 [00:28<00:00, 1049.46it/s]
 99%|█████████▊| 29623/30000 [00:28<00:00, 1047.73it/s]
 99%|█████████▉| 29731/30000 [00:28<00:00, 1056.58it/s]
 99%|█████████▉| 29837/30000 [00:28<00:00, 996.31it/s]
100%|██████████| 30000/30000 [00:28<00:00, 1042.10it/s][A

entered train

1it [00:47, 47.78s/it]

entered val
entered test_non_sys
entered test_sys

In [14]:
test_sys_data['indexing_method']

88       Curated
94       Curated
99         Human
986        Human
987        Human
          ...
29509      Human
29536      Human
29538      Human
29573      Human
29803    Curated
Name: indexing_method, Length: 111, dtype: object

In [32]:
val_subset = data_pd[data_pd['year']==2015]

In [32]:
# num_to_select = None

# filenames = glob.glob('/data/iain/pubmed/*.gz')

# # done_jsons = glob.glob('../robotlabs/trialstreamer/classifications/*.json')
# # done_files = [os.path.join('../robotlabs/trialstreamer/data/', os.path.splitext(os.path.basename(f))[0] + '.gz') for f in done_jsons]

# # files_todo = list(set(filenames) - set(done_files))
# num_todo = len(filenames)

# # all_data = []

# is_article_data = False
# article_data = pd.DataFrame()

# # NOTE to Gregory
# # To run the full version of this will take a long time (since 300 million articles in 900 files)
# # I suggest to run the version below with a single file (which will take a minute or two)
# # to refine the strategy, and then when all is good run it across the full set (by uncommenting and commenting the lines below)


# # for i, fn in tqdm.tqdm(enumerate(filenames[33:])): # this line does *all* >900 files (takes ages)

# # for id in range(len(filenames)):
# for i, fn in tqdm.tqdm(enumerate([filenames[900]])): # file 900 looks to me to be a decent example; perhaps others better! but some earlier abstracts don't contain much info


#         # here we're iterating through *all* files
#         # in the final version, probably we'd want to randomly sample, to generate a manageable amount of data
#         # I suspect we might not have enough RAM to hold all 300M articles at once, (and so you will need to sample in the loop)
#         # but possibly it might work without this, and you could sample from the Pandas dataframe below instead!
#         sys.__stdout__.write("file number {}/{} ({}) processing \n".format(i, num_todo, fn)) # optional to see progress from terminal
#         print("file number {}/{} ({}) processing \n".format(i, num_todo, fn))
#         data = []
#         print(fn)
#         for article in iter_abstracts(fn, num_to_select):
#             data.append(article)
            
#         data_pd = pd.DataFrame(data)
#         data_pd = data_pd[data_pd['year'] != '']
#         data_pd['year'] = list(map(int, data_pd['year']))
#         data_pd = data_pd[data_pd['year']>1987]
        

# #         all_data.extend(data)
#         if not is_article_data:
#             article_data = data_pd
#             is_article_data = True
#         else:
#             article_data = pd.concat([article_data, data_pd])
    
# #     article_data = pd.DataFrame(all_data)
# #     ptyps = []

# #     for ptyprow in article_data['ptyp']:
# #         ptyps.extend(ptyprow)

# #     ptyps = list(set(ptyps))
# #     for ptyp in ptyps:
# #         if 'gov' in ptyp.lower():
# #             print(ptyp)

0it [00:00, ?it/s]

file number 0/1062 (/data/iain/pubmed/pubmed21n0905.xml.gz) processing

/data/iain/pubmed/pubmed21n0905.xml.gz

  0%|          | 0/30000 [00:00<?, ?it/s]
  1%|          | 162/30000 [00:00<00:18, 1613.94it/s]
  1%|          | 324/30000 [00:00<00:18, 1607.09it/s]
  2%|▏         | 521/30000 [00:00<00:16, 1769.35it/s]
  2%|▏         | 698/30000 [00:00<00:17, 1649.20it/s]
  3%|▎         | 865/30000 [00:00<00:18, 1597.10it/s]
  3%|▎         | 1026/30000 [00:00<00:18, 1574.21it/s]
  4%|▍         | 1185/30000 [00:00<00:18, 1579.08it/s]
  4%|▍         | 1344/30000 [00:00<00:18, 1566.46it/s]
  5%|▌         | 1501/30000 [00:00<00:18, 1558.48it/s]
  6%|▌         | 1658/30000 [00:01<00:18, 1559.76it/s]
  6%|▌         | 1819/30000 [00:01<00:17, 1572.39it/s]
  7%|▋         | 1977/30000 [00:01<00:19, 1433.46it/s]
  7%|▋         | 2125/30000 [00:01<00:19, 1444.09it/s]
  8%|▊         | 2272/30000 [00:01<00:19, 1426.54it/s]
  8%|▊         | 2425/30000 [00:01<00:18, 1455.49it/s]
  9%|▊         | 2572/30000 [00:01<00:19, 1416.50it/s]
  9%|▉         | 2727/30000 [00:01<00:18, 1454.46it/s]
 10%|▉         | 2936/30000 [00:01<00:16, 1637.53it/s]
 10%|█         | 3124/30000 [00:01<00:15, 1707.56it/s]
 11%|█         | 3296/30000 [00:02<00:15, 1705.00it/s]
 12%|█▏        | 3475/30000 [00:02<00:15, 1729.50it/s]
 12%|█▏        | 3649/30000 [00:02<00:15, 1683.50it/s]
 13%|█▎        | 3832/30000 [00:02<00:15, 1722.86it/s]
 13%|█▎        | 4005/30000 [00:02<00:15, 1708.13it/s]
 14%|█▍        | 4178/30000 [00:02<00:15, 1713.73it/s]
 15%|█▍        | 4354/30000 [00:02<00:14, 1723.82it/s]
 15%|█▌        | 4527/30000 [00:02<00:15, 1686.83it/s]
 16%|█▌        | 4696/30000 [00:02<00:15, 1670.33it/s]
 16%|█▌        | 4864/30000 [00:03<00:16, 1553.28it/s]
 17%|█▋        | 5034/30000 [00:03<00:15, 1592.78it/s]
 17%|█▋        | 5205/30000 [00:03<00:15, 1623.10it/s]
 18%|█▊        | 5418/30000 [00:03<00:13, 1769.38it/s]
 19%|█▊        | 5597/30000 [00:03<00:14, 1651.01it/s]
 19%|█▉        | 5765/30000 [00:03<00:15, 1574.09it/s]
 20%|█▉        | 5925/30000 [00:03<00:15, 1533.11it/s]
 20%|██        | 6080/30000 [00:03<00:15, 1508.87it/s]
 21%|██        | 6274/30000 [00:03<00:14, 1628.91it/s]
 22%|██▏       | 6484/30000 [00:04<00:13, 1762.21it/s]
 22%|██▏       | 6662/30000 [00:04<00:13, 1710.10it/s]
 23%|██▎       | 6835/30000 [00:04<00:13, 1714.53it/s]
 23%|██▎       | 7009/30000 [00:04<00:13, 1720.50it/s]
 24%|██▍       | 7197/30000 [00:04<00:12, 1763.31it/s]
 25%|██▍       | 7374/30000 [00:04<00:13, 1687.29it/s]
 25%|██▌       | 7544/30000 [00:04<00:13, 1652.27it/s]
 26%|██▌       | 7710/30000 [00:04<00:13, 1605.08it/s]
 26%|██▌       | 7872/30000 [00:04<00:13, 1584.03it/s]
 27%|██▋       | 8031/30000 [00:04<00:13, 1577.30it/s]
 27%|██▋       | 8189/30000 [00:05<00:13, 1571.62it/s]
 28%|██▊       | 8347/30000 [00:05<00:13, 1558.55it/s]
 28%|██▊       | 8505/30000 [00:05<00:13, 1564.78it/s]
 29%|██▉       | 8674/30000 [00:05<00:13, 1598.01it/s]
 29%|██▉       | 8840/30000 [00:05<00:13, 1614.40it/s]
 30%|███       | 9002/30000 [00:05<00:13, 1553.96it/s]
 31%|███       | 9158/30000 [00:05<00:14, 1483.09it/s]
 31%|███       | 9308/30000 [00:05<00:14, 1439.04it/s]
 32%|███▏      | 9457/30000 [00:05<00:14, 1449.13it/s]
 32%|███▏      | 9603/30000 [00:06<00:14, 1445.61it/s]
 32%|███▏      | 9748/30000 [00:06<00:14, 1413.86it/s]
 33%|███▎      | 9890/30000 [00:06<00:14, 1376.84it/s]
 33%|███▎      | 10046/30000 [00:06<00:13, 1429.01it/s]
 34%|███▍      | 10196/30000 [00:06<00:13, 1449.40it/s]
 35%|███▍      | 10361/30000 [00:06<00:13, 1508.08it/s]
 35%|███▌      | 10513/30000 [00:06<00:13, 1496.30it/s]
 36%|███▌      | 10717/30000 [00:06<00:11, 1655.39it/s]
 36%|███▋      | 10888/30000 [00:06<00:11, 1666.43it/s]
 37%|███▋      | 11056/30000 [00:06<00:11, 1621.95it/s]
 37%|███▋      | 11219/30000 [00:07<00:11, 1614.43it/s]
 38%|███▊      | 11381/30000 [00:07<00:11, 1607.00it/s]
 38%|███▊      | 11544/30000 [00:07<00:11, 1613.53it/s]
 39%|███▉      | 11706/30000 [00:07<00:13, 1401.29it/s]
 40%|███▉      | 11852/30000 [00:07<00:16, 1110.44it/s]
 40%|████      | 12012/30000 [00:07<00:14, 1222.32it/s]
 41%|████      | 12170/30000 [00:07<00:13, 1309.56it/s]
 41%|████      | 12335/30000 [00:07<00:12, 1396.93it/s]
 42%|████▏     | 12483/30000 [00:08<00:12, 1387.11it/s]
 42%|████▏     | 12628/30000 [00:08<00:12, 1364.77it/s]
 43%|████▎     | 12773/30000 [00:08<00:12, 1387.19it/s]
 43%|████▎     | 12915/30000 [00:08<00:12, 1373.22it/s]
 44%|████▎     | 13069/30000 [00:08<00:11, 1417.68it/s]
 44%|████▍     | 13232/30000 [00:08<00:11, 1476.31it/s]
 45%|████▍     | 13382/30000 [00:08<00:11, 1472.03it/s]
 45%|████▌     | 13531/30000 [00:08<00:11, 1456.34it/s]
 46%|████▌     | 13678/30000 [00:08<00:11, 1426.38it/s]
 46%|████▌     | 13847/30000 [00:08<00:10, 1502.57it/s]
 47%|████▋     | 14007/30000 [00:09<00:10, 1528.88it/s]
 47%|████▋     | 14161/30000 [00:09<00:10, 1526.39it/s]
 48%|████▊     | 14327/30000 [00:09<00:10, 1563.62it/s]
 48%|████▊     | 14500/30000 [00:09<00:09, 1612.34it/s]
 49%|████▉     | 14666/30000 [00:09<00:09, 1625.49it/s]
 49%|████▉     | 14829/30000 [00:09<00:09, 1562.70it/s]
 50%|████▉     | 14986/30000 [00:09<00:09, 1557.07it/s]
 50%|█████     | 15148/30000 [00:09<00:09, 1574.73it/s]
 51%|█████     | 15306/30000 [00:09<00:09, 1566.87it/s]
 52%|█████▏    | 15469/30000 [00:09<00:09, 1581.84it/s]
 52%|█████▏    | 15637/30000 [00:10<00:08, 1609.04it/s]
 53%|█████▎    | 15799/30000 [00:10<00:08, 1587.34it/s]
 53%|█████▎    | 15958/30000 [00:10<00:09, 1538.39it/s]
 54%|█████▎    | 16113/30000 [00:10<00:09, 1493.52it/s]
 54%|█████▍    | 16263/30000 [00:10<00:09, 1476.87it/s]
 55%|█████▍    | 16467/30000 [00:10<00:08, 1638.70it/s]
 56%|█████▌    | 16668/30000 [00:10<00:07, 1746.30it/s]
 56%|█████▌    | 16870/30000 [00:10<00:07, 1822.71it/s]
 57%|█████▋    | 17054/30000 [00:10<00:07, 1788.38it/s]
 57%|█████▋    | 17234/30000 [00:11<00:07, 1698.95it/s]
 58%|█████▊    | 17406/30000 [00:11<00:07, 1617.96it/s]
 59%|█████▊    | 17572/30000 [00:11<00:07, 1626.97it/s]
 59%|█████▉    | 17736/30000 [00:11<00:07, 1614.29it/s]
 60%|█████▉    | 17899/30000 [00:11<00:07, 1605.08it/s]
 60%|██████    | 18060/30000 [00:11<00:07, 1505.86it/s]
 61%|██████    | 18227/30000 [00:11<00:07, 1550.68it/s]
 61%|██████▏   | 18392/30000 [00:11<00:07, 1577.57it/s]
 62%|██████▏   | 18551/30000 [00:11<00:07, 1559.42it/s]
 62%|██████▏   | 18708/30000 [00:11<00:07, 1520.42it/s]
 63%|██████▎   | 18861/30000 [00:12<00:07, 1485.93it/s]
 63%|██████▎   | 19011/30000 [00:12<00:07, 1479.56it/s]
 64%|██████▍   | 19176/30000 [00:12<00:07, 1528.30it/s]
 64%|██████▍   | 19344/30000 [00:12<00:06, 1569.89it/s]
 65%|██████▌   | 19502/30000 [00:12<00:06, 1509.62it/s]
 66%|██████▌   | 19654/30000 [00:12<00:07, 1476.73it/s]
 66%|██████▌   | 19822/30000 [00:12<00:06, 1534.73it/s]
 67%|██████▋   | 19977/30000 [00:12<00:06, 1518.16it/s]
 67%|██████▋   | 20130/30000 [00:12<00:06, 1515.28it/s]
 68%|██████▊   | 20282/30000 [00:13<00:06, 1464.97it/s]
 68%|██████▊   | 20429/30000 [00:13<00:06, 1459.78it/s]
 69%|██████▊   | 20584/30000 [00:13<00:06, 1485.90it/s]
 69%|██████▉   | 20733/30000 [00:13<00:06, 1482.87it/s]
 70%|██████▉   | 20887/30000 [00:13<00:06, 1497.96it/s]
 70%|███████   | 21072/30000 [00:13<00:05, 1600.22it/s]
 71%|███████   | 21270/30000 [00:13<00:05, 1712.57it/s]
 71%|███████▏  | 21449/30000 [00:13<00:04, 1735.08it/s]
 72%|███████▏  | 21623/30000 [00:13<00:04, 1675.48it/s]
 73%|███████▎  | 21792/30000 [00:13<00:04, 1643.11it/s]
 73%|███████▎  | 21957/30000 [00:14<00:04, 1639.63it/s]
 74%|███████▎  | 22122/30000 [00:14<00:05, 1546.04it/s]
 74%|███████▍  | 22281/30000 [00:14<00:04, 1557.94it/s]
 75%|███████▍  | 22438/30000 [00:14<00:04, 1551.78it/s]
 75%|███████▌  | 22598/30000 [00:14<00:04, 1564.32it/s]
 76%|███████▌  | 22758/30000 [00:14<00:04, 1574.19it/s]
 76%|███████▋  | 22923/30000 [00:14<00:04, 1594.31it/s]
 77%|███████▋  | 23083/30000 [00:14<00:04, 1593.18it/s]
 77%|███████▋  | 23243/30000 [00:14<00:04, 1550.13it/s]
 78%|███████▊  | 23399/30000 [00:15<00:04, 1521.21it/s]
 79%|███████▊  | 23552/30000 [00:15<00:04, 1484.29it/s]
 79%|███████▉  | 23701/30000 [00:15<00:04, 1446.64it/s]
 79%|███████▉  | 23846/30000 [00:15<00:04, 1353.22it/s]
 80%|███████▉  | 23983/30000 [00:15<00:04, 1335.72it/s]
 80%|████████  | 24118/30000 [00:15<00:04, 1326.98it/s]
 81%|████████  | 24309/30000 [00:15<00:03, 1490.24it/s]
 82%|████████▏ | 24491/30000 [00:15<00:03, 1582.80it/s]
 82%|████████▏ | 24651/30000 [00:15<00:03, 1518.04it/s]
 83%|████████▎ | 24807/30000 [00:15<00:03, 1529.82it/s]
 83%|████████▎ | 24961/30000 [00:16<00:03, 1523.17it/s]
 84%|████████▍ | 25161/30000 [00:16<00:02, 1661.73it/s]
 84%|████████▍ | 25329/30000 [00:16<00:02, 1633.64it/s]
 85%|████████▍ | 25494/30000 [00:16<00:02, 1611.80it/s]
 86%|████████▌ | 25656/30000 [00:16<00:02, 1601.96it/s]
 86%|████████▌ | 25817/30000 [00:16<00:02, 1594.50it/s]
 87%|████████▋ | 25987/30000 [00:16<00:02, 1624.72it/s]
 87%|████████▋ | 26150/30000 [00:16<00:02, 1594.00it/s]
 88%|████████▊ | 26310/30000 [00:16<00:02, 1533.51it/s]
 88%|████████▊ | 26464/30000 [00:17<00:02, 1525.30it/s]
 89%|████████▉ | 26644/30000 [00:17<00:02, 1602.70it/s]
 89%|████████▉ | 26805/30000 [00:17<00:01, 1599.11it/s]
 90%|████████▉ | 26966/30000 [00:17<00:01, 1536.47it/s]
 90%|█████████ | 27121/30000 [00:17<00:01, 1447.24it/s]
 91%|█████████ | 27278/30000 [00:17<00:01, 1480.25it/s]
 92%|█████████▏| 27488/30000 [00:17<00:01, 1656.12it/s]
 92%|█████████▏| 27688/30000 [00:17<00:01, 1754.60it/s]
 93%|█████████▎| 27911/30000 [00:17<00:01, 1889.33it/s]
 94%|█████████▍| 28141/30000 [00:17<00:00, 2008.11it/s]
 94%|█████████▍| 28350/30000 [00:18<00:00, 2025.85it/s]
 95%|█████████▌| 28562/30000 [00:18<00:00, 2051.97it/s]
 96%|█████████▌| 28768/30000 [00:18<00:00, 1924.78it/s]
 97%|█████████▋| 28963/30000 [00:18<00:00, 1820.36it/s]
 97%|█████████▋| 29148/30000 [00:18<00:00, 1762.62it/s]
 98%|█████████▊| 29326/30000 [00:18<00:00, 1725.21it/s]
 98%|█████████▊| 29500/30000 [00:18<00:00, 1678.03it/s]
 99%|█████████▉| 29670/30000 [00:18<00:00, 1683.57it/s]
100%|██████████| 30000/30000 [00:19<00:00, 1573.10it/s]
1it [00:42, 42.73s/it]

In [33]:
len(article_data)

28176

In [24]:
article_data = pd.DataFrame(all_data)

In [25]:
# and here is the final dataset, which can be saved as a CSV
article_data = article_data[article_data['year'] != '']
article_data['year'] = list(map(int, article_data['year']))
article_data_modern = article_data[article_data['year']>1987]

In [28]:
article_data_modern

,title,abstract,authors,journal,journal_abbrv,year,mesh,month,volume,issue,pages,ptyp,pmid,registry_ids,dois
0,"Targeting HDAC3, a new partner protein of AKT ...","[{'header': '_UNSTRUCTURED', 'text': 'Resistan...","[{'Initials': 'J', 'LastName': 'Long', 'ForeNa...",Leukemia,Leukemia,2017,"[Animals, Antineoplastic Agents, Cell Line, Tu...",12,31,12,"{'page_from': '2761', 'page_to': '2770'}","[Journal Article, Research Support, Non-U.S. G...",28462918,[],[10.1038/leu.2017.130]
1,Targeting antigen-independent proliferation in...,"[{'header': '_UNSTRUCTURED', 'text': 'The clin...","[{'Initials': 'E', 'LastName': 'Slinger', 'For...",Leukemia,Leukemia,2017,"[Antigens, Neoplasm, Biomarkers, CD40 Antigens...",12,31,12,"{'page_from': '2601', 'page_to': '2607'}",[Journal Article],28462919,[],[10.1038/leu.2017.129]
2,Evaluating the association of single-nucleotid...,"[{'header': '_UNSTRUCTURED', 'text': 'Higher e...","[{'Initials': 'SM', 'LastName': 'Baxi', 'ForeN...",The pharmacogenomics journal,Pharmacogenomics J,2018,"[ATP Binding Cassette Transporter, Subfamily G...",04,18,2,"{'page_from': '245', 'page_to': '250'}","[Journal Article, Research Support, N.I.H., Ex...",28462920,[],[10.1038/tpj.2017.3]
3,One amino acid makes a difference-Characteriza...,"[{'header': '_UNSTRUCTURED', 'text': 'Thiopuri...","[{'Initials': 'YPH', 'LastName': 'Iu', 'ForeNa...",Scientific reports,Sci Rep,2017,"[Alleles, Genotype, Humans, Methyltransferases...",05,7,,"{'page_from': '46428', 'page_to': '46428'}","[Journal Article, Research Support, Non-U.S. G...",28462921,[],[10.1038/srep46428]
4,Corrigendum: A Comparison of Rule-based Analys...,[],"[{'Initials': 'M', 'LastName': 'Haghighi', 'Fo...",Scientific reports,Sci Rep,2017,[],05,7,,"{'page_from': '39723', 'page_to': '39723'}","[Journal Article, Published Erratum]",28462922,[],[10.1038/srep39723]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,Why we need fairer allocation rules for patien...,[],"[{'Initials': 'HJ', 'LastName': 'Metselaar', '...",Transplant international : official journal of...,Transpl Int,2017,"[Carcinoma, Hepatocellular, Humans, Liver Neop...",11,30,11,"{'page_from': '1092', 'page_to': '1094'}","[Journal Article, Comment]",28493615,[],[10.1111/tri.12980]
29996,Impact of a webcast on nurses' delivery of tob...,"[{'header': 'AIMS AND OBJECTIVES', 'text': 'To...","[{'Initials': 'L', 'LastName': 'Sarna', 'ForeN...",Journal of clinical nursing,J Clin Nurs,2018,"[Adult, Attitude of Health Personnel, Evidence...",Jan,27,1-2,"{'page_from': 'e91', 'page_to': 'e99'}","[Comparative Study, Journal Article]",28493616,[],[10.1111/jocn.13875]
29997,Anti-inflammatory bioactive equivalence of com...,"[{'header': '_UNSTRUCTURED', 'text': 'Bioactiv...","[{'Initials': 'Y', 'LastName': 'Cui', 'ForeNam...",Journal of separation science,J Sep Sci,2017,"[Alkaloids, Anti-Inflammatory Agents, Arenaria...",Jul,40,14,"{'page_from': '2895', 'page_to': '2905'}",[Journal Article],28493617,[],[10.1002/jssc.201700144]
29998,Pondering practice: Enhancing the art of refle...,"[{'header': 'AIMS AND OBJECTIVES', 'text': 'Th...","[{'Initials': 'C', 'LastName': 'Hayes', 'ForeN...",Journal of clinical nursing,J Clin Nurs,2018,"[Clinical Competence, Education, Nursing, Bacc...",Jan,27,1-2,"{'page_from': 'e345', 'page_to': 'e353'}",[Journal Article],28493618,[],[10.1111/jocn.13876]
29999,Access to Hexahydrocarbazoles: The Thorpe-Ingo...,"[{'header': '_UNSTRUCTURED', 'text': 'A novel ...","[{'Initials': 'H', 'LastName': 'Chen', 'ForeNa...",Angewandte Chemie (International ed. in English),Angew Chem Int Ed Engl,2017,[],06,56,24,"{'page_from': '6942', 'page_to': '6945'}","[Journal Article, Research Support, Non-U.S. G...",28493619,[],[10.1002/anie.201700042]

In [9]:
article_data.describe()

,title,abstract,authors,journal,journal_abbrv,year,mesh,month,volume,issue,pages,ptyp,pmid,registry_ids,dois
count,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000
unique,2980,2591,2972,1554,1553,13,2240,25,275,95,2667,156,3000,39,2895
top,,[],[],PloS one,PLoS One,2017,[],,12,,"{'page_from': '', 'page_to': ''}",[Journal Article],28473154,[],[]
freq,16,410,22,56,56,2498,761,514,110,505,151,1510,1,2962,106

In [15]:
set(article_data['year'])

{'',
 '1976',
 '1981',
 '1986',
 '1991',
 '1993',
 '1997',
 '1998',
 '2000',
 '2001',
 '2002',
 '2003',
 '2004',
 '2005',
 '2008',
 '2010',
 '2011',
 '2012',
 '2013',
 '2014',
 '2015',
 '2016',
 '2017',
 '2018',
 '2019',
 '2020'}

In [15]:
article_data.columns

Index(['title', 'abstract', 'authors', 'journal', 'journal_abbrv', 'year',
       'mesh', 'month', 'volume', 'issue', 'pages', 'ptyp', 'pmid',
       'registry_ids', 'dois'],
      dtype='object')

In [16]:
ptyps = []

for ptyprow in article_data['ptyp']:
    ptyps.extend(ptyprow)
    
ptyps = set(ptyps)

In [17]:
ptyps

{'Address',
 'Autobiography',
 'Biography',
 'Case Reports',
 'Classical Article',
 'Clinical Conference',
 'Clinical Study',
 'Clinical Trial',
 'Clinical Trial, Phase I',
 'Clinical Trial, Phase II',
 'Clinical Trial, Phase III',
 'Clinical Trial, Phase IV',
 'Comment',
 'Comparative Study',
 'Congress',
 'Consensus Development Conference',
 'Consensus Development Conference, NIH',
 'Controlled Clinical Trial',
 'Dataset',
 'Editorial',
 'English Abstract',
 'Equivalence Trial',
 'Evaluation Study',
 'Expression of Concern',
 'Festschrift',
 'Guideline',
 'Historical Article',
 'Interview',
 'Introductory Journal Article',
 'Journal Article',
 'Lecture',
 'Letter',
 'Meta-Analysis',
 'Multicenter Study',
 'News',
 'Observational Study',
 'Patient Education Handout',
 'Personal Narrative',
 'Portrait',
 'Practice Guideline',
 'Pragmatic Clinical Trial',
 'Published Erratum',
 'Randomized Controlled Trial',
 'Research Support, N.I.H., Extramural',
 'Research Support, N.I.H., Intramural',
 "Research Support, Non-U.S. Gov't",
 "Research Support, U.S. Gov't, Non-P.H.S.",
 "Research Support, U.S. Gov't, P.H.S.",
 'Retracted Publication',
 'Retraction of Publication',
 'Review',
 'Systematic Review',
 'Technical Report',
 'Twin Study',
 'Validation Study',
 'Video-Audio Media'}

In [18]:
proposed_design_types = [
    
    # Propose to compress these into single category
    'Editorial',
    'Address',
    'Letter',
    'Lecture',
    #######################################
    'Adaptive Clinical Trial',
    
     
    
    # Propose to compress these into single category
    'Clinical Trial',
    'Clinical Trial, Phase I', 
    'Clinical Trial, Phase II', 
    'Clinical Trial, Phase III',
    'Clinical Trial, Phase IV',
    #######################################
    'Clinical Trial Protocol',
    
    # Propose to compress these into single category
    'Consensus Development Conference',
    'Consensus Development Conference, NIH',
    ########################################
    
    # Propose to compress these into single category
    'Guideline',
    'Practice Guideline',
    ########################################
    
    'Case Reports',
    'Controlled Clinical Trial',
    'Observational Study',
    'Randomized Controlled Trial',
    'Comment',
    'Comparative Study',
    'Equivalence Trial',
    'Evaluation Study',
    'Government Publications',
    'Randomized Controlled Trial',
    'Government Publication',
    'Meta-Analysis',
    'Personal Narrative',
    'Pragmatic Clinical Trial',
    'Review',
    'Systematic Review',
    'Validation Study'

]

In [33]:
article_data.to_csv('pubmed_articles.csv')

In [37]:
proposed_design_types

['Editorial',
 'Address',
 'Letter',
 'Lecture',
 'Adaptive Clinical Trial',
 'Clinical Trial',
 'Clinical Trial, Phase I',
 'Clinical Trial, Phase II',
 'Clinical Trial, Phase III',
 'Clinical Trial, Phase IV',
 'Clinical Trial Protocol',
 'Consensus Development Conference',
 'Consensus Development Conference, NIH',
 'Guideline',
 'Practice Guideline',
 'Case Reports',
 'Controlled Clinical Trial',
 'Observational Study',
 'Randomized Controlled Trial',
 'Comment',
 'Comparative Study',
 'Equivalence Trial',
 'Evaluation Study',
 'Government Publications',
 'Randomized Controlled Trial',
 'Government Publication',
 'Meta-Analysis',
 'Personal Narrative',
 'Pragmatic Clinical Trial',
 'Review',
 'Systematic Review',
 'Validation Study']

In [41]:
[ set(ptyps).intersection(set(proposed_design_types)) ==set() for ptyps in article_data['ptyp']]

[True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 False,
 False,
 True,
 False,
 True,
 True,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 True,
 True,
 True,
 False,
 True,
 False,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 False,
 False,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 False,
 True,
 True,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 True,
 True,
 False,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 False,
 True,
 True,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 True,
 True,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 False,
 False,
 True,
 False,
 True,
 True,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 True,
 False,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 True,
 True,
 False,
 True,
 True,
 False,
 True,
 True,
 True,
 False,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 True,
 True,
 True,
 True,
 False,
 False,
 True,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 True,
 True,
 False,
 True,
 False,
 False,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 True,
 False,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 False,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 False,
 True,
 True,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 True,
 False,
 True,
 True,
 False,
 True,
 False,
 True,
 True,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 True,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 True,
 True,
 True,
 False,
 False,
 True,
 False,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 True,
 False,
 False,
 False,
 True,
 True,
 True,
 False,
 True,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 ...]

In [43]:
pos_articles = article_data[[ set(ptyps).intersection(set(proposed_design_types)) ==set() for ptyps in article_data['ptyp']] ]

In [44]:
neg_articles = article_data[[ set(ptyps).intersection(set(proposed_design_types)) !=set() for ptyps in article_data['ptyp']] ]

In [45]:
len(pos_articles)

20298

In [46]:
len(neg_articles)

9702

In [49]:
len(article_data)

30000

In [13]:
# num_types_per_art = [0]
# for i in range(len(article_data)):
#     art = article_data.loc[i]
#     for art in art['ptyp']:
#         if art in proposed_design_types:
#             num_types_per_art[-1]+=1
#     num_types_per_art.append(0)

In [14]:
# clashes = [(article_data.iloc[i], num_types_per_art[i]) for i in range(len(num_types_per_art)) if num_types_per_art[i]>1]
# print(clashes)
# print(len(clashes))

[(title            European evidence-based recommendations for di...
abstract         [{'header': '_UNSTRUCTURED', 'text': 'Antiphos...
authors          [{'Initials': 'N', 'LastName': 'Groot', 'ForeN...
journal                           Annals of the rheumatic diseases
journal_abbrv                                        Ann Rheum Dis
year                                                          2017
mesh             [Adolescent, Antiphospholipid Syndrome, Child,...
month                                                          Oct
volume                                                          76
issue                                                           10
pages                     {'page_from': '1637', 'page_to': '1641'}
ptyp             [Journal Article, Practice Guideline, Review, ...
pmid                                                      28473426
registry_ids                                                    []
dois                             [10.1136/annrheumdis-2016-211001]
Name: 10198, dtype: object, 2), (title            Tight controlled dose reduction of biologics i...
abstract         [{'header': 'BACKGROUND', 'text': 'Psoriasis i...
authors          [{'Initials': 'S', 'LastName': 'Atalay', 'Fore...
journal                                            BMC dermatology
journal_abbrv                                         BMC Dermatol
year                                                          2017
mesh             [Adalimumab, Administration, Topical, Adult, A...
month                                                           05
volume                                                          17
issue                                                            1
pages                           {'page_from': '6', 'page_to': '6'}
ptyp             [Equivalence Trial, Journal Article, Multicent...
pmid                                                      28482858
registry_ids                                         [NCT02602925]
dois                                   [10.1186/s12895-017-0057-6]
Name: 19503, dtype: object, 2), (title            Italian COnsensus in Neuroradiological Anesthe...
abstract         [{'header': '_UNSTRUCTURED', 'text': 'Anesthet...
authors          [{'Initials': 'CA', 'LastName': 'Castioni', 'F...
journal                                    Minerva anestesiologica
journal_abbrv                                   Minerva Anestesiol
year                                                          2017
mesh             [Anesthesia, Endovascular Procedures, Humans, ...
month                                                          Sep
volume                                                          83
issue                                                            9
pages                       {'page_from': '956', 'page_to': '971'}
ptyp             [Consensus Development Conference, Journal Art...
pmid                                                      28492296
registry_ids                                                    []
dois                              [10.23736/S0375-9393.17.11753-0]
Name: 28742, dtype: object, 2)]
3

In [15]:

# for i in range(len(article_data)):
#     if 'Observational Study' in article_data.iloc[i]['ptyp'] and 'Randomized Controlled Trial' in article_data.iloc[i]['ptyp']:
#         clash = article_data.iloc[i]
#         break

In [16]:
# clash['title']

'Polyphenol Levels Are Inversely Correlated with Body Weight and Obesity in an Elderly Population after 5 Years of Follow Up (The Randomised PREDIMED Study).'

In [18]:
# clash['abstract']

[{'header': '_UNSTRUCTURED',
  'text': 'Overweight and obesity have been steadily increasing in recent years and currently represent a serious threat to public health. Few human studies have investigated the relationship between polyphenol intake and body weight. Our aim was to assess the relationship between urinary polyphenol levels and body weight. A cross-sectional study was performed with 573 participants from the PREDIMED (Prevención con Dieta Mediterránea) trial (ISRCTN35739639). Total polyphenol levels were measured by a reliable biomarker, total urinary polyphenol excretion (TPE), determined by the Folin-Ciocalteu method in urine samples. Participants were categorized into five groups according to their TPE at the fifth year. Multiple linear regression models were used to assess the relationships between TPE and obesity parameters; body weight (BW), body mass index (BMI), waist circumference (WC), and waist-to-height ratio (WHtR). After a five years follow up, significant inverse correlations were observed between TPE at the 5th year and BW (β = -1.004; 95% CI: -1.634 to -0.375, p = 0.002), BMI (β = -0.320; 95% CI: -0.541 to -0.098, p = 0.005), WC (β = -0.742; 95% CI: -1.326 to -0.158, p = 0.013), and WHtR (β = -0.408; 95% CI: -0.788 to -0.028, p = 0.036) after adjustments for potential confounders. To conclude, a greater polyphenol intake may thus contribute to reducing body weight in elderly people at high cardiovascular risk.'}]

<function pandas.core.reshape.concat.concat(objs: Union[Iterable[ForwardRef('NDFrame')], Mapping[Union[Hashable, NoneType], ForwardRef('NDFrame')]], axis=0, join='outer', ignore_index: bool = False, keys=None, levels=None, names=None, verify_integrity: bool = False, sort: bool = False, copy: bool = True) -> Union[ForwardRef('DataFrame'), ForwardRef('Series')]>